New filter & Config file
trackit/trackit pull request #108
Opened 2018-08-31 23:31 UTC by thibautcornolti

* Added new filters
* Added variables in the config file

2018-09-03 09:33 UTC, simonmeyerrr submitted a review, later dismissed

2018-09-04 09:41 UTC, zanchi-r commented
@thibautcornolti I don't see any modifications in the config file, did you forget to push it?

2018-09-04 11:33 UTC, zanchi-r commented
go install github.com/trackit/trackit-server/server                                                    ttys001 13:28:09 04/09/2018
# github.com/trackit/trackit-server/costs/anomalies
src/github.com/trackit/trackit-server/costs/anomalies/anomalies.go:72:26: undefined: "github.com/trackit/trackit-server/config".AnomalyDetectionLevels
src/github.com/trackit/trackit-server/costs/anomalies/anomalies.go:84:32: undefined: "github.com/trackit/trackit-server/config".AnomalyDetectionPrettyLevels
src/github.com/trackit/trackit-server/costs/anomalies/anomalies.go:136:40: undefined: "github.com/trackit/trackit-server/config".AnomalyDetectionDisturbanceCleaningHighestSpendingPeriod
src/github.com/trackit/trackit-server/costs/anomalies/anomalies.go:158:18: undefined: "github.com/trackit/trackit-server/config".AnomalyDetectionDisturbanceCleaningHighestSpendingMinRank
src/github.com/trackit/trackit-server/costs/anomalies/anomalies.go:170:49: undefined: "github.com/trackit/trackit-server/config".AnomalyDetectionDisturbanceCleaningMinPercentOfDailyBill
src/github.com/trackit/trackit-server/costs/anomalies/anomalies.go:170:137: undefined: "github.com/trackit/trackit-server/config".AnomalyDetectionDisturbanceCleaningMinAbsoluteCost
src/github.com/trackit/trackit-server/costs/anomalies/anomalies.go:208:33: undefined: "github.com/trackit/trackit-server/config".AnomalyDetectionBollingerBandPeriod
src/github.com/trackit/trackit-server/costs/anomalies/anomalies.go:213:23: undefined: "github.com/trackit/trackit-server/config".AnomalyDetectionBollingerBandUpperBandCoefficient
src/github.com/trackit/trackit-server/costs/anomalies/anomalies.go:213:95: undefined: "github.com/trackit/trackit-server/config".AnomalyDetectionBollingerBandStandardDeviationCoefficient
src/github.com/trackit/trackit-server/costs/anomalies/es_request_constructor.go:41:34: undefined: "github.com/trackit/trackit-server/config".AnomalyDetectionBollingerBandPeriod

2018-09-04 11:42 UTC, zanchi-r requested changes

2018-09-04 11:42 UTC, zanchi-r commented on server/taskAnomaliesDetection.go
> +		} else if an.Level < config.AnomalyEmailingMinLevel {
All the Anomaly parameters are missing in the config parameters

2018-09-05 14:46 UTC, zanchi-r approved these changes

2018-09-05 14:46 UTC, merged