[TRAC-1005] Optimize usage reports
trackit/trackit pull request #155
Opened 2018-10-25 09:18 UTC by simonmeyerrr

This PR:

### - Changes the mapping in ES for RDS and EC2
Now each instance is saved in a document.

### - Update endpoints and ingest for RDS and EC2
To be compliant with the new mapping

### - Optimize ES and AWS calls

2018-10-25 12:46 UTC, thibautcornolti requested changes
Review in progress
(some changes on mappings)

2018-10-25 12:46 UTC, thibautcornolti commented on aws/usageReports/ec2/mappings.go
>  {
Your mapping isn't well readable, it should be:
- cpu
  - peak
  - average
- network
  - in
  - out....

2018-10-25 15:29 UTC, thibautcornolti requested changes

2018-10-25 15:29 UTC, thibautcornolti commented on aws/usageReports/ec2/monthlyReport.go
> +func fetchMonthlyInstancesList(ctx context.Context, creds *credentials.Credentials, inst utils.CostPerResource,
Please do not forget comments above the functions as well as the function name.

2018-10-25 15:29 UTC, thibautcornolti commented on aws/usageReports/ec2/mappings.go
> +				"cost": {
`cost` seems useless to me since we can calculate it from `costDetail`.

2018-10-25 15:29 UTC, thibautcornolti commented on aws/usageReports/ec2/mappings.go
> +				"tags": {
```
tags: [
	{
		name: string
		value: string
	}
]
```
is better for later to do aggregations

2018-10-26 16:23 UTC, thibautcornolti requested changes
Still some minor changes to do

2018-10-26 16:23 UTC, thibautcornolti commented on aws/usageReports/ec2/utils.go
> +	// Instance contains the information of an EC2 instance
You shouldn't use the same structure with ES and as a result of the request.
To avoid duplicates, you can do a common struct.
```
InstanceBase struct {
  Id string
  Region...
}

InstanceEsResult {
  InstanceBase
  Tags []Tag
}

InstanceResponse {
  InstanceBase
  Tags map[string]string
}
```

2018-10-26 16:23 UTC, thibautcornolti commented on aws/usageReports/rds/mappings.go
>  						"dbInstanceIdentifier": {
`identifier` should be enough

2018-10-26 16:23 UTC, thibautcornolti commented on aws/usageReports/rds/mappings.go
> +						"dbInstanceClass": {
`type` is better

2018-10-30 12:57 UTC, hug33k approved these changes

2018-10-30 12:57 UTC, hug33k commented on usageReports/ec2/prepare_response.go
> +	"time"
This import should not be here

2018-10-31 10:37 UTC, merged