Endpoint to get AWS Accounts status
trackit/trackit pull request #167
Opened 2018-11-09 12:38 UTC by hug33k

This PR adds a new endpoint (`/aws/status`) that returns every users' AWS Account with their bill repositories and also their statuses.

This endpoint cas be used to check if there is an issue with AWS Account or bill repositories configuration.

2018-11-09 14:16 UTC, thibautcornolti requested changes

2018-11-09 14:16 UTC, thibautcornolti commented on aws/routes/routeAwsStatus.go
> +func getAwsAccountsStatus(r *http.Request, a routes.Arguments) (int, interface{}) {
You should keep your types. `(int, []awsAccountWithStatus, error)` would be better.

2018-11-09 14:16 UTC, thibautcornolti commented on aws/routes/routeAwsStatus.go
> +func getLastJobs(tx *sql.Tx, billRepositoriesIds []int) (map[int]job, error) {
Any heavy SQL code should be located in `models/awsbillupdatejob.go`.

2018-11-09 14:16 UTC, thibautcornolti commented on aws/routes/routeAwsStatus.go
> +	var sqlstr = `
You should create a view and, if you can, get values with XO.

2018-11-09 14:17 UTC, thibautcornolti commented on aws/routes/routeAwsStatus.go
> +	result := make([]interface{}, 0)
No need to use `interface` here.

2018-11-15 12:38 UTC, zanchi-r approved these changes

2018-11-15 12:39 UTC, merged