Add ElasticSearch, ElastiCache & Lamba usage reports into spreadsheet reports
trackit/trackit pull request #194
Opened 2018-12-07 17:03 UTC by hug33k

This PR adds 3 sheets into spreadsheet reports :
- ElasticSearch Usage Reports
- ElastiCache Usage Reports
- Lambda Usage Reports

2018-12-10 09:41 UTC, simonmeyerrr commented on db/migration/0033_add_elasticache_and_elasticsearch_to_spreadsheet_reports.sql
> +  elasticacheUsageReportError VARCHAR(255) NOT NULL DEFAULT "",
error to copy and paste, there is a duplicate + bad indentation on each line

2018-12-10 16:11 UTC, simonmeyerrr approved these changes

2018-12-12 09:15 UTC, zanchi-r commented
@hug33k please fix the conflicts and rename the migration file, 0033 already exist

2018-12-12 09:15 UTC, zanchi-r requested changes
please fix the conflicts and rename the migration file, 0033 already exist

2018-12-12 09:20 UTC, hug33k commented
@zanchi-r Done

2018-12-12 15:17 UTC, zanchi-r approved these changes

2018-12-12 15:17 UTC, merged