Add RI reports into spreadsheet reports
trackit/trackit pull request #210
Opened 2019-01-08 13:46 UTC by hug33k

This PR adds two new sheets into spreadsheet reports :
- Reserved Instances report for EC2
- Reserved Instances report for RDS

This PR adds also a fix for filename generation (When generating a spreadsheet report for December, month was `0` instead of `12`).

2019-01-09 15:51 UTC, zanchi-r approved these changes

2019-01-18 14:47 UTC, thibautcornolti commented on reports/report_generation.go
> +		previousMonth := now.Month() - 1
```go
d := time.Now().AddDate(0, -1, 0)
d.Month().String()
d.Year()
```

2019-01-18 14:53 UTC, thibautcornolti requested changes
Be aware that making a slice of 0 as length and append _n_ times a elem is slow, you should make a slice of _n_.

2019-01-18 14:53 UTC, thibautcornolti commented on reports/ri_ec2.go
> +	chargesFrequency := make([]string, 0)
You can use `len(reservation.RecurringCharges)` instead of 0. So that, it won't allocate again and again memory.

2019-01-18 14:53 UTC, thibautcornolti commented on reports/ri_ec2.go
> +	data = make([][]cell, 0)
Same here, use `len(riEc2InstanceFormat)`

2019-01-18 14:53 UTC, thibautcornolti commented on reports/ri_rds.go
> +	chargesFrequency := make([]string, 0)
Same here

2019-01-18 14:53 UTC, thibautcornolti commented on reports/ri_rds.go
> +	data = make([][]cell, 0)
Again

2019-01-18 16:11 UTC, thibautcornolti requested changes

2019-01-18 16:11 UTC, thibautcornolti commented on reports/utils.go
> +}
You've forgot a new line.

2019-01-18 16:11 UTC, thibautcornolti commented on reports/utils.go
> +	"github.com/trackit/trackit-server/aws"
Bad order

2019-01-18 16:14 UTC, thibautcornolti approved these changes

2019-01-22 12:42 UTC, zanchi-r requested changes

2019-01-22 12:42 UTC, zanchi-r commented on db/migration/0037_ri_es_and_rds_into_spreadsheet_reports.sql
> +--   Copyright 2018 MSolution.IO
Please rename to 0038_ri_es_and_rds_into_spreadsheet_reports.sql

2019-01-23 09:06 UTC, zanchi-r approved these changes

2019-01-23 09:06 UTC, merged