Added route to add anomaly filters
trackit/trackit pull request #212
Opened 2019-01-10 14:44 UTC by thibautcornolti

2019-01-10 16:26 UTC, hug33k submitted a review, later dismissed

2019-01-10 16:26 UTC, hug33k commented on costs/anomalies/filters_route.go
> +	"errors"
Wrong order for imports

2019-01-10 16:26 UTC, hug33k commented on costs/anomalies/filters_route.go
> +		"absolute_date_max": "2019-01-01 00:00:00",
Why not using ISO 8601 format? (e.g. : `2019-01-01T00:00:00Z` )
Existing endpoints that needs to return a date are using this format.

2019-01-10 16:26 UTC, hug33k commented on costs/anomalies/filters_route.go
> +		"expected_cost_max": 100.0,
What if value type in request body is an `int` ?

2019-01-10 16:26 UTC, hug33k commented on costs/anomalies/filters_route.go
> +		"relative_date_max": "3600",
What does these two values mean ?

2019-01-10 16:26 UTC, hug33k commented on costs/anomalies/filters_route.go
> +	for rule, dataType := range availableRules {
Why not using `dataType, ok = availableRules[filter.Rule]` ?

2019-01-10 16:26 UTC, hug33k commented on costs/anomalies/filters_route.go
> +			return http.StatusBadRequest, errors.New(filter.Rule + ": bad rule")
Error response should be more specific (Rule name is invalid, rule data type is invalid, ...)

2019-01-17 15:45 UTC, hug33k requested changes

2019-01-17 15:45 UTC, hug33k commented on costs/anomalies/anomalyFilters/product.go
> +			if product == p {
Can you make it case insensitive ? Otherwise "EC2" and "ec2" would act differently.

2019-01-17 15:45 UTC, hug33k commented on costs/anomalies/filters_route.go
> +	"github.com/trackit/trackit-server/costs/anomalies/anomalyType"
Import order is wrong

2019-01-17 15:45 UTC, hug33k commented on costs/anomalies/filters_route.go
> +						Data: []string{"NeededProduct1", "NeededProduct2"},
Add `Disabled` in example

2019-01-17 16:22 UTC, zanchi-r approved these changes

2019-01-17 16:23 UTC, hug33k approved these changes

2019-01-17 16:27 UTC, merged