On demand to ri ec2 report
trackit/trackit pull request #218
Opened 2019-01-31 14:37 UTC by zanchi-r

This PR adds the on demand to RI ec2 report generation.
A new task fetch-pricings was created to retrieve the pricings and should be run by nomad every 24 hours.
The report is generated during the process-account task and saved into ES.

2019-02-01 15:45 UTC, thibautcornolti requested changes

2019-02-01 15:45 UTC, thibautcornolti commented on aws/pricings/fetchEc2Pricings.go
> +type Specs struct {
The struct name should be more precise.

2019-02-01 15:45 UTC, thibautcornolti commented on aws/pricings/fetchEc2Pricings.go
> +type Platform struct {
Again

2019-02-01 15:45 UTC, thibautcornolti commented on aws/pricings/fetchEc2Pricings.go
> +type Type struct {
Again

2019-02-01 15:45 UTC, thibautcornolti commented on aws/pricings/fetchEc2Pricings.go
> +func isCurrentGeneration(item aws.JSONValue) *bool {
Why did you use a pointer here?

2019-02-01 16:41 UTC, thibautcornolti approved these changes

2019-02-08 14:58 UTC, thibautcornolti approved these changes

2019-02-08 16:05 UTC, hug33k approved these changes

2019-02-08 16:06 UTC, merged