[Spreadsheets] S3 Cost Report
trackit/trackit pull request #231
Opened 2019-07-08 11:19 UTC by whosdad

Create a new page in the spreadsheets which is called S3 Cost Report.

This page contain information about S3 Cost Report:

- Instance
- Billable Size ( in GigaBytes )
- Costs : Storage, Bandwidth, Requests and Total
- Data Transfers ( in GigaBytes ) : In / Out

![s3CostReportSpreadsheetPR](https://user-images.githubusercontent.com/47174238/60806304-efa68980-a182-11e9-9dc2-8a492767e778.png)

2019-07-08 15:02 UTC, hug33k requested changes

2019-07-08 15:02 UTC, hug33k commented on reports/module_s3_cost_report.go
> +	}
You can directly return after `if` without using `else`

2019-07-08 15:02 UTC, hug33k commented on reports/module_s3_cost_report.go
> +func s3CostReportInsertDataInSheet(_ context.Context, file *excelize.File, data map[aws.AwsAccount]costs.BucketsInfo) (err error) {
Since you are not using `context.Context`, you can remove it from arguments

2019-07-08 15:02 UTC, hug33k commented on s3/update_s3_cost_functions_&_exports.patch
> +Index: s3/costs/s3_costs_route.go
This file should not be there…

2019-07-10 09:24 UTC, whosdad commented on s3/update_s3_cost_functions_&_exports.patch
> +Index: s3/costs/s3_costs_route.go
Fixed

2019-07-10 09:24 UTC, whosdad commented on reports/module_s3_cost_report.go
> +func s3CostReportInsertDataInSheet(_ context.Context, file *excelize.File, data map[aws.AwsAccount]costs.BucketsInfo) (err error) {
Fixed

2019-07-10 09:24 UTC, whosdad commented on reports/module_s3_cost_report.go
> +	}
Fixed

2019-07-30 11:50 UTC, hug33k approved these changes

2019-07-30 11:51 UTC, merged