ElasticSearch upgrade
trackit/trackit pull request #238
Opened 2019-07-29 15:31 UTC by Dayrion1

ElasticSearch (ES) has been upgraded to 6.8 on staging and will be upgrade to 6.7 on production. Along to this upgrade, the ES library for the API has been updated and older versions has been removed from the `vendor` (for govendor) file.
The tool `go fmt` has been used in almost every folder because of the huge amount of edited files due to the ES library upgrade so, there is a lot of little changes accross the repository.
After a short discussion with @hug33k, there was a mistake in the `README.md` file and has been corrected.

2019-07-30 12:00 UTC, giubil requested changes
LGTM, except for a few comments left

2019-07-30 12:00 UTC, giubil commented on es/billingRepository.go
> +	//"github.com/olivere/elastic"
You have a comment that shouldn't be here

2019-07-30 12:00 UTC, giubil commented on es/client.go
> +	//"github.com/olivere/elastic"
Dito

2019-07-30 12:00 UTC, giubil commented on vendor/vendor.json
> +>>>>>>> cfa4129... ES API Library upgrade to 6.2.21 along with the ES 6.* upgrade + Removed obsolete ES API library + Usage of go fmt almost every folder due to huge amount of files edited.
Forgot to remove a merge conflict comment

2019-07-30 12:00 UTC, giubil commented on vendor/vendor.json
> +	"rootPath": "github.com/trackit/trackit"
If this is changed only in this PR, does it mean that if we deploy stg right now it will be broken ?

2019-07-30 12:03 UTC, giubil commented on vendor/vendor.json
> +	"rootPath": "github.com/trackit/trackit"
Nevermind, this fix was already merged in `stg`

2019-07-30 12:15 UTC, giubil requested changes

2019-07-30 12:15 UTC, giubil commented on vendor/vendor.json
> -		{
Is this unused ? Why was this removed ?

2019-07-30 12:16 UTC, giubil commented on vendor/vendor.json
> -		{
Ah we changed libraries, nevermind

2019-07-30 12:16 UTC, giubil approved these changes

2019-08-06 16:27 UTC, hug33k requested changes

2019-08-06 16:27 UTC, hug33k commented on aws/usageReports/ec2/monthlyReport.go
> +	"github.com/olivere/elastic"
Wrong import order

2019-08-06 16:27 UTC, hug33k commented on aws/usageReports/history/history.go
> +	"github.com/olivere/elastic"
Wrong import order

2019-08-06 16:27 UTC, hug33k commented on es/client.go
> +	"github.com/olivere/elastic"
Wrong import order

2019-08-06 16:27 UTC, hug33k commented on es/simplifyCostsDocument.go
> +	"github.com/olivere/elastic"
Wrong import order

2019-08-07 13:07 UTC, hug33k approved these changes

2019-08-07 13:07 UTC, merged