Add optional parameters to Process Account task
trackit/trackit pull request #252
Opened 2019-09-11 13:28 UTC by Dayrion1

The task to ingest account data can now take 2 optional parameters. It allow to ingest data at a specific month & year like master spreadsheet task does.

2019-09-12 15:57 UTC, cruffinoni commented
Quick explanation of the bug solved on the last commit:
When performing the task of acquiring billing data and creating a file identifier, if the current file already has the same type (ec2,...), the same time stamp as an existing file but not the same type of report (daily vs. monthly report); the task generates the same file identifier and refuses consumption. We have changed the way identities are created to solve the problem.

2019-12-03 14:04 UTC, hug33k requested changes

2019-12-03 14:04 UTC, hug33k commented on aws/usageReports/instanceCount/utils.go
> +		ReportType       string    `json:"reportType"`
Indentation

2019-12-03 14:04 UTC, hug33k commented on server/taskProcessAccount.go
> +	onDemandToRiEc2 "github.com/trackit/trackit/onDemandToRI/ec2"
Wrong import order

2019-12-03 14:08 UTC, hug33k requested changes

2019-12-03 14:08 UTC, hug33k commented on aws/usageReports/history/history.go
> +	fmt.Printf("Start history at '%v' & '%v'\n", startDate, endDate)
Please remove

2019-12-03 14:10 UTC, jgchoppe approved these changes

2019-12-03 14:21 UTC, hug33k approved these changes

2019-12-03 15:19 UTC, merged