[Events] Fix issues on anomalies filters and on anomalies snoozing
trackit/trackit pull request #255
Opened 2019-11-18 13:58 UTC by jgchoppe

This PR is about the issue we had on anomalies filters and anomalies snoozing (the fact that we couldn't add or delete filters and we couldn't snooze or unsnooze anomalies).

2019-11-18 16:04 UTC, hug33k approved these changes

2019-11-18 16:04 UTC, hug33k commented on costs/anomalies/anomalies_route.go
> +	"github.com/trackit/trackit/cache"
Wrong import order

2019-11-18 16:04 UTC, hug33k commented on costs/anomalies/anomalies_route.go
> +			cache.UsersCache{},
Why did you moved this line ?

2019-11-18 16:04 UTC, hug33k commented on costs/anomalies/filters_route.go
> +	"net/http"
Wrong import order

2019-11-18 16:04 UTC, hug33k commented on costs/anomalies/filters_route.go
> +}
Missing new line

2019-11-18 16:04 UTC, hug33k commented on costs/anomalies/snoozing_route.go
> +	"net/http"
Wrong import order

2019-11-18 16:04 UTC, hug33k requested changes
See comments

2019-11-18 16:28 UTC, closed without merging

2019-11-19 19:23 UTC, Dr0p42 commented
@jgchoppe I don't know which IDE/Text editor you are using, but most of them have plugins that can run `gofmt` and `goimports` fo you when saving your files ;)