[Feature] Elemental Task w/ mediaconvert & medialive monthly/daily ingest in ES
trackit/trackit pull request #264
Opened 2019-12-11 13:46 UTC by jgchoppe

This PR is about the new task "elemental-process-account". This task ingest in the ElasticSearch data about Elemental Products. In this PR there is also the Elemental MediaConvert & MediaLive monthly/daily ingest.

2019-12-16 10:10 UTC, Dr0p42 commented
@jgchoppe where are we about this pull request? Is it still in progress?

2019-12-17 14:01 UTC, hug33k requested changes

2019-12-17 14:01 UTC, hug33k commented on server/taskProcessAccount.go
> +	onDemandToRiEc2 "github.com/trackit/trackit/onDemandToRI/ec2"
Wrong input order

2019-12-17 14:01 UTC, hug33k commented on server/taskElementalProcessAccount.go
> +	_, err := db.Exec(sqlstr, time.Now(), errToStr(jobErr), errToStr(historyErr), medialiveChannelsErr, medialiveInputsErr, mediaconvertErr, historyCreated, updateId)
Why do you only `errToStr` only on `jobErr` and `historyErr` ?

2019-12-17 14:01 UTC, hug33k commented on db/migration/0044_add_elemental_process_account_task.sql
> +	aws_account_id 				 INTEGER      NOT NULL,
Indentation

2019-12-17 14:01 UTC, hug33k commented on db/migration/0044_add_elemental_process_account_task.sql
> +	mediaLiveInputsError   VARCHAR(255) NOT NULL DEFAULT "",
Why `medialive` then `mediaLive` ?

2019-12-17 14:01 UTC, hug33k commented on db/migration/0044_add_elemental_process_account_task.sql
> +--   Copyright 2017 MSolution.IO
This migration should be added at the end of `db/schema.sql` also

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/history/history.go
> +}
Missing `\n`

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/history/history.go
> +	logger.Info("Starting history report", map[string]interface{}{
Replace message with `"Starting Elemental history report"`

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/mediaconvert/costJobs.go
> +	"github.com/trackit/jsonlog"
This import should be below `"github.com/olivere/elastic"`

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/mediaconvert/costJobs.go
> +	})
Please remove debug log

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/mediaconvert/costJobs.go
> +	})
Please remove debug log

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/mediaconvert/dailyReport.go
> +	taws "github.com/trackit/trackit/aws"
Missing `\n` above this import

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/mediaconvert/dailyReport.go
> +			Cost:         0,
Did you used `gofmt` for indentation ?

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/mediaconvert/monthlyReport.go
> +	"github.com/trackit/trackit/es"
Wrong import order

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/mediaconvert/monthlyReport.go
> +	}*/
🤔

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/mediaconvert/utils.go
> +		Cost                 float64           `json:"cost"`
Indentation

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/channelCosts.go
> +	"github.com/aws/aws-sdk-go/aws"
Wrong import order

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/channelCosts.go
> +	startDate = time.Date(now.Year()-1, now.Month()-1, 1, 0, 0, 0, 0, now.Location()).UTC() // line to remove
🤔

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/channelCosts.go
> +	fmt.Printf("response = %v\n", res)
Please remove debug print

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/dailyReport.go
> +	fmt.Printf("listInput = %v\n", listInput)
Please remove debug log

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/dailyReport.go
> +		fmt.Printf("Error when listing channels for medialive: %v\n", err)
Please remove debug print

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/dailyReport.go
> +		fmt.Printf("error input medialive = %v\n", err)
Please remove debug log

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/fetchChannelsInputs.go
> +			log.Printf("REGION = %v\n", region)
Please remove debug log

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/mappingsChannels.go
> +						},
🤔

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/mappingsInput.go
> +						},
🤔

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/monthlyReport.go
> +}
Missing `\n`

2019-12-17 14:01 UTC, hug33k commented on aws/usageReports/medialive/monthlyReport.go
> +// and filled by DescribeChannels and getChannelStats.
🤔

2019-12-17 16:16 UTC, jgchoppe commented on aws/usageReports/medialive/mappingsChannels.go
> +						},
@hug33k I don't see the issue ?

2019-12-17 16:23 UTC, jgchoppe commented on aws/usageReports/mediaconvert/dailyReport.go
> +			Cost:         0,
yes

2020-08-25 09:24 UTC, alexandre-snr commented
This task was related to a project which was cancelled in favor of Tagbot.

2020-08-25 09:24 UTC, closed without merging