Feature/task update tags
trackit/trackit pull request #275
Opened 2020-07-02 12:32 UTC by alexandre-snr

This PR adds the 'update-tags' task.

This task uses the lastest daily usage reports to generate tagging reports.
These tagging reports contains resource's type, id, region, url and the tags associated with this resource.

The tagging reports are stored in a new ES index called *-tagging-reports for further usage.
All supported resources are implemented (still need an example URL to build the Elasticache url model)

Tests were made with the used mapping and it should be OK for the usage we would have (most used tags, resources without a specified tag ...)

2020-07-02 15:03 UTC, jklakosz reviewed
Good for me except the missing `\n`. Waiting for @simonmeyerrr approval.

2020-07-02 15:03 UTC, jklakosz commented on tagging/mappings.go
> +	"github.com/trackit/jsonlog"
Missing `\n` at the end of line.

2020-07-02 19:31 UTC, jklakosz approved these changes
Good for me, waiting for @simonmeyerrr approval.

2020-07-03 07:51 UTC, simonmeyerrr requested changes
Apply corrections I asked for `tagging/ebs/process.go` for every other similar files.

2020-07-03 07:51 UTC, simonmeyerrr commented on db/migration/0044_add_aws_account_update_tags_job.sql
> +);
Add a newline please

2020-07-03 07:51 UTC, simonmeyerrr commented on db/schema.sql
> +);
Add a new line please

2020-07-03 07:51 UTC, simonmeyerrr commented on db/schema.sql
> +	job_error               VARCHAR(255) NOT NULL DEFAULT "",
not aligned

2020-07-03 07:51 UTC, simonmeyerrr commented on tagging/ebs/process.go
> +	logger.Info(fmt.Sprintf("%d %s reports processed.", len(documents), resourceTypeString), nil)
If you want to log some values, use a map[string]interface{} as second parameter instead of using fmt.Sprintf

2020-07-03 07:51 UTC, simonmeyerrr commented on tagging/ebs/process.go
> +	logger.Info(fmt.Sprintf("Processing %s reports.", resourceTypeString), nil)
If you want to log some values, use a map[string]interface{} as second parameter instead of using fmt.Sprintf

2020-07-03 07:51 UTC, simonmeyerrr commented on tagging/ebs/process.go
> +		logger.Error(fmt.Sprintf("Could not process a %s report.", resourceTypeString), nil)
If you want to log some values, use a map[string]interface{} as second parameter instead of using fmt.Sprintf

2020-07-03 07:51 UTC, simonmeyerrr commented on tagging/ebs/es.go
> +func fetchReports(ctx context.Context, account int) ([]*elastic.SearchHit, error) {
please split this function

2020-07-03 07:51 UTC, simonmeyerrr commented on tagging/mappings.go
> +			},
bad indentation

2020-07-06 14:38 UTC, simonmeyerrr approved these changes

2020-07-15 14:15 UTC, simonmeyerrr requested changes
Make sure to use good Ids everywhere

2020-07-15 14:15 UTC, simonmeyerrr commented on tagging/ec2Ri/process.go
> +type reservation struct {
Use the structure from the original package

2020-07-15 14:15 UTC, simonmeyerrr commented on tagging/ec2Ri/process.go
> +const sourceIndexName = "ri-ec2-reports"
Use the index name from the original package

2020-07-16 08:00 UTC, simonmeyerrr requested changes

2020-07-16 08:00 UTC, simonmeyerrr commented on server/taskUpdateTags.go
> +	amazonAccountID, err := checkUpdateTagsArguments(args)
rename variable into  `aaId` to be consistent with the rest of the code

2020-07-16 08:00 UTC, simonmeyerrr commented on server/taskUpdateTags.go
> +func updateTagsForAccount(ctx context.Context, amazonAccountID int) error {
please follow the format of the function `ingestDataForAccount`

2020-07-16 08:00 UTC, simonmeyerrr commented on tagging/ebs/es.go
> +	topHitsAggregation := elastic.NewTopHitsAggregation().Size(2147483647).FetchSourceContext(elastic.NewFetchSourceContext(true).Include("account", "snapshot.id", "snapshot.region", "snapshot.tags"))
use the format with only one variable to be consistent with the rest of the code

2020-07-16 08:00 UTC, simonmeyerrr commented on tagging/ebs/process.go
> +const urlFormat = "https://%s.console.aws.amazon.com/ec2/v2/home?region=%s#Snapshots:all;search=%s"
You can remove the first region for all urls before `.console.`

2020-07-16 12:31 UTC, simonmeyerrr approved these changes

2020-07-16 12:34 UTC, merged