Feature/most used tags
trackit/trackit pull request #278
Opened 2020-07-16 12:38 UTC by alexandre-snr

This PR adds the task update-most-used-tags which takes the most used tags out of the last tagging report and stores them in the SQL Db.

2020-07-16 13:58 UTC, simonmeyerrr requested changes

2020-07-16 13:58 UTC, simonmeyerrr commented on server/taskUpdateMostUsedTags.go
> +	return nil
should return err

2020-07-16 13:58 UTC, simonmeyerrr commented on tagging/routes/routeGetMostUsedTags.go
> +package routes
missing headers

2020-07-16 13:58 UTC, simonmeyerrr commented on tagging/routes/routes.go
> +			routes.QueryArgs(mostUsedTagsQueryArgs),
don't need to set query args if you don't use them

2020-07-16 13:59 UTC, jklakosz reviewed
Seems globally good for me, not tested by my side.

2020-07-17 08:48 UTC, simonmeyerrr approved these changes

2020-07-17 08:50 UTC, merged