Feature/tagging resources
trackit/trackit pull request #281
Opened 2020-07-20 07:59 UTC by SchneiderNicolas

This PR adds the route in API to get a list of resources. This route sends an ES request and return the list of resources in a JSON format.
You can also filter resources and get them by region and resources type.

2020-07-20 08:07 UTC, alexandre-snr reviewed
Not much to say, waiting for Simon and Jules' approvals

2020-07-20 08:07 UTC, alexandre-snr commented on resourcesTagging/prepareResponse.go
> +	"github.com/trackit/trackit/tagging/utils"
New line misplaced

2020-07-20 08:07 UTC, alexandre-snr commented on resourcesTagging/routes.go
> +	"github.com/trackit/trackit/db"
Missing new line

2020-07-20 08:12 UTC, simonmeyerrr requested changes

2020-07-20 08:12 UTC, simonmeyerrr commented on resourcesTagging/getResourcesData.go
> +}
missing new line

2020-07-20 08:12 UTC, simonmeyerrr commented on resourcesTagging/prepareResponse.go
> +}
missing new line

2020-07-20 08:12 UTC, simonmeyerrr commented on resourcesTagging/routes.go
> +}
missing new line

2020-07-20 08:12 UTC, simonmeyerrr commented on server/server.go
> +	_ "github.com/trackit/trackit/resourcesTagging"
you should put your code in existing package `tagging/routes`

2020-07-20 08:12 UTC, simonmeyerrr commented on resourcesTagging/routes.go
> +		Region       []string
Add a `s` for all variables that contain arrays to better identify them

2020-07-20 08:59 UTC, jklakosz requested changes

2020-07-20 08:59 UTC, jklakosz commented on resourcesTagging/esRequestConstructor.go
> +
2 new lines, only 1 is good enough

2020-07-20 11:50 UTC, jklakosz commented on tagging/routes/prepareResponse.go
> +
this line space must be at 23rd line

2020-07-20 11:52 UTC, alexandre-snr approved these changes

2020-07-20 11:52 UTC, jklakosz approved these changes

2020-07-21 07:28 UTC, simonmeyerrr requested changes

2020-07-21 07:28 UTC, simonmeyerrr commented on tagging/routes/routes.go
> +		Name:        "region",
missing `s`

2020-07-21 07:28 UTC, simonmeyerrr commented on tagging/routes/routes.go
> +		Name:        "resourceType",
missing `s`

2020-07-21 09:47 UTC, simonmeyerrr approved these changes

2020-07-21 11:02 UTC, merged