Feature/should popup
trackit/trackit pull request #304
Opened 2020-08-19 14:07 UTC by SchneiderNicolas

This PR add a route that verify if the user has access to Tagbot (marketplace subscription, stripe subscription or free trial).

And returns whether or not to display the popup that asks the user to subscribe.

2020-08-19 14:13 UTC, alexandre-snr requested changes

2020-08-19 14:13 UTC, alexandre-snr commented on tagging/routes/routeGetShouldPopup.go
> +}
`CustomerIdentifier != ""` checks are not needed. Entitlement flags are false by default if there are none.
Also could you replace `200` codes  by `http.StatusOK` please ?

2020-08-19 14:27 UTC, alexandre-snr approved these changes
LGTM

2020-08-20 09:51 UTC, hug33k requested changes

2020-08-20 09:51 UTC, hug33k commented on tagging/routes/routes.go
> +				Description: "Responds with the list of resources based on the queryparams passed to it",
Description does not reflect the purpose of this endpoint

2020-08-20 11:34 UTC, hug33k approved these changes

2020-08-20 12:10 UTC, merged