Feat/cloud formation tag
trackit/trackit pull request #329
Opened 2021-07-15 14:21 UTC by J3suis

Add CloudFormationUrl to Report Document for Tagbot

2021-07-15 15:42 UTC, GabrielRavier requested changes

2021-07-15 15:42 UTC, GabrielRavier commented on tagging/utils/documents.go
> +
Is this empty line supposed to be there ?

2021-07-15 15:42 UTC, GabrielRavier commented on tagging/updateTags.go
> +		documents[i] = documents[i].GenCloudFormationUrl()
Wouldn't it make more sense for this to be written without the assignment (with `GenCloudFormationUrl` taking its argument by pointer) ?

2021-07-15 15:42 UTC, GabrielRavier commented on tagging/utils/cloudFormationUrl.go
> +func (doc TaggingReportDocument) GenCloudFormationUrl() TaggingReportDocument {
It seems like it would make more sense to put this function directly in `documents.go`

2021-07-16 07:38 UTC, EthanHusser reviewed
Nothing to say for this version.

2021-07-16 08:21 UTC, simonmeyerrr approved these changes

2021-07-16 08:22 UTC, EthanHusser approved these changes

2021-07-16 08:22 UTC, GabrielRavier approved these changes
LGTM now

2021-07-16 08:23 UTC, merged