Feat/update most used tags
trackit/trackit pull request #338
Opened 2021-07-29 14:18 UTC by J3suis

- Add a ways to see all mostusedtags history by user with routes /tagging/mostusedtags-history
- Link most used tags to /tagging/compliance response

2021-07-30 09:51 UTC, GabrielRavier requested changes

2021-07-30 09:51 UTC, GabrielRavier commented on tagging/routes/routeGetMostUsedTags.go
> +		return http.StatusInternalServerError, nil
From what I can see in other code, you can also return the details of the error as the second return value is an `interface{}` and something like `error` will be handled perfectly well, as can be seen from code in `users/create.go`, for example.

2021-07-30 09:51 UTC, GabrielRavier commented on tagging/routes/routeGetMostUsedTags.go
> +		return http.StatusInternalServerError, map[string]interface{}{
Same here, you don't have to return a `map[string]interface{}`, you can just go and return something like `errors.New("No history reports available")` (unless the `map[string]interface{}` looks much better or something like that)

2021-07-30 09:51 UTC, GabrielRavier commented on tagging/routes/routes.go
> +			},
This documentation seems inaccurate, considering it's a copy-paste of the one from `/tagging/mostusedtags`

2021-07-30 10:07 UTC, GabrielRavier approved these changes
LGTM now

2021-09-09 14:04 UTC, simonmeyerrr requested changes

2021-09-09 14:04 UTC, simonmeyerrr commented on tagging/routes/routeGetMostUsedTags.go
> +		return http.StatusInternalServerError, errors.New("no history reports available")
Should be a `404` error

2021-09-09 14:04 UTC, simonmeyerrr commented on tagging/routes/routeGetMostUsedTags.go
> +			return http.StatusInternalServerError, err
Use `continue` so a little error does not block the user to get valid history data.

2021-09-09 14:04 UTC, simonmeyerrr commented on tagging/routes/routeGetMostUsedTags.go
> +		if mut == nil || len(tagsList) == 0 {
It's to late to check if `mut` is nil as you already use it earlier

2021-09-22 08:48 UTC, simonmeyerrr approved these changes

2021-09-22 08:48 UTC, merged