Cleaned up a *lot* of places where errors are ignored or otherwise badly handled
trackit/trackit pull request #349
Opened 2021-08-25 14:05 UTC by GabrielRavier

Note: You might want to see whether it might be better in some places to throw the error back up the call stack to end up being reported elsewhere, I might have possibly been overly careful in some places as I wanted to avoid the chances of false positives as much as possible (i.e. there's a bunch of places where I just log the error and do nothing else with it).

I also corrected a few task name typos in server while I was at it since they were right next to the errors, but do tell me if that should go into another PR

2021-08-27 08:17 UTC, cruffinoni requested changes
I'm waiting for @simonmeyerrr or someone else to do a review before merging.

2021-08-27 08:17 UTC, cruffinoni commented on server/utils.go
> +//   Copyright 2017 MSolution.IO
Shouldn't you put 2021?

2021-08-27 08:17 UTC, cruffinoni commented on users/password.go
> +			if rec != nil || err != nil {
`err` will be always null in this condition

2021-08-27 11:18 UTC, GabrielRavier commented on server/utils.go
> +//   Copyright 2017 MSolution.IO
Oops, that was a copy-paste error. Corrected it !

2021-08-27 12:43 UTC, GabrielRavier commented on users/password.go
> +			if rec != nil || err != nil {
It's in a deferred function so it can be non-nil after the call to `models.DeleteExpiredForgottenPassword`

2021-09-09 13:49 UTC, simonmeyerrr approved these changes

2021-09-09 13:49 UTC, merged