Fixed loads of spelling errors
trackit/trackit pull request #350
Opened 2021-08-26 14:23 UTC by GabrielRavier

A majority of these are in comments but a lot of them are in error messages and often in stuff that'll be returned to the web client and visible to its user

2021-08-27 08:33 UTC, cruffinoni requested changes

2021-08-27 08:33 UTC, cruffinoni commented on aws/usageReports/riEc2/utils.go
> +	// RecurringCharges contains recurring charges information for a reservation
I'm not sure about this one.

2021-08-27 08:33 UTC, cruffinoni commented on aws/usageReports/riRdS/utils.go
> +	// RecurringCharges contains recurring charges information for a reservation
Same as above, I'm not sure about this one.

2021-08-27 08:33 UTC, cruffinoni commented on routes/constError.go
> +// constError is a string which fulfills the error interface.
`fills` can also be used here. What do you think?

2021-08-27 08:34 UTC, cruffinoni reviewed
I'm not asking for changes but I am questioning some of them. There is no approval or disapproval here, it's my fault!

2021-08-27 12:48 UTC, GabrielRavier commented on routes/constError.go
> +// constError is a string which fulfills the error interface.
I think that "fulfilling an interface" makes more sense than filling it

2021-08-27 12:50 UTC, GabrielRavier commented on aws/usageReports/riRdS/utils.go
> +	// RecurringCharges contains recurring charges information for a reservation
I'll return to this one once we've handled the one above

2021-08-27 12:50 UTC, GabrielRavier commented on aws/usageReports/riEc2/utils.go
> +	// RecurringCharges contains recurring charges information for a reservation
What do you mean, exactly ? I'm pretty sure information can't be used in plural (except when talking about court filings, but that's not exactly the case here). Though I guess it might be "the recurring charges information of a reservation" rather than "recurring charges information for a reservation" but it seems more likely to me to be the latter

2021-09-09 13:52 UTC, simonmeyerrr approved these changes

2021-09-09 14:27 UTC, simonmeyerrr approved these changes

2021-09-09 14:27 UTC, merged