Replaced every AWSAccountId param from Int or []Int to String or []String
trackit/trackit pull request #61
Opened 2018-07-12 13:10 UTC by thibautcornolti

2018-07-13 09:36 UTC, zanchi-r requested changes

2018-07-13 09:36 UTC, zanchi-r commented on costs/diff/diff_route.go
> +		parsedParams.accountList = a[diffQueryArgs[0]].([]string)
This creates a panic: diffQueryArgs[0] uses routes.AwsAccountsOptionalQueryArg which is a []int, you cannot cast it to []string

2018-07-13 11:29 UTC, simonmeyerrr submitted a review, later dismissed

2018-07-17 12:46 UTC, zanchi-r approved these changes

2018-07-17 12:46 UTC, merged