sends an email to viewer to set password when a viewer account is created
trackit/trackit pull request #83
Opened 2018-08-03 13:47 UTC by Cramix

2018-08-06 08:28 UTC, zanchi-r requested changes
I was not able to compile this:
src/github.com/trackit/trackit-server/users/create.go:147:11: undefined: uuid
src/github.com/trackit/trackit-server/users/create.go:150:3: undefined: logger
src/github.com/trackit/trackit-server/users/create.go:169:12: undefined: time
src/github.com/trackit/trackit-server/users/create.go:173:3: undefined: logger
src/github.com/trackit/trackit-server/users/create.go:180:3: undefined: logger

2018-08-10 08:45 UTC, zanchi-r requested changes
Just a small change and the PR will be ready

2018-08-10 08:45 UTC, zanchi-r commented on users/create.go
> +	mailBody := fmt.Sprintf("Please follow this link to create your password: https://re.trackit.io/reset/%d/%s.", viewerUser.Id, token)
The first parameter should be dbForgottenPassword.ID instead of viewerUser.Id

2018-08-10 12:07 UTC, bastienk commented
I pushed the changes you required

2018-08-10 13:43 UTC, merged