Feature/share account team organization
trackit/trackit pull request #99
Opened 2018-08-24 14:25 UTC by Lolincolc

This PR adds an enpoint to share an account with another user whether it exists or not. It also adds a new table in the DB.

New endpoint : /user/invite
The endpoint takes three parameters : 

- Email : the mail of the invited user
- AccountId : the AWS account ID (from table aws_account) that the user wants to share access to
- PermissionLevel : the permission level (0 : admin access, 1 : standard user access, 2 : read-only user)

### How this is working :
- If the user does not exist, a new account is created with a temporary password randomly generated as a placeholder in the DB. A Forgotten password token is also generated allowing the user to choose his password before first login. Then, a new entry in table shared_account is inserted (see shared_account detail section).
- If the user already exist, a new entry is inserted in table shared_account

Users then receive an email that inform them that a new account has been added to their account. If the user didn't exist previously, the user is invited to create his account with the reset password link provided in the mail.

### New shared_account table details : 
- id: the id of the new entry
- account_id: the AWS account id that is being shared
- owner_id: user id of the user who is inviting someone else
- user_id : user id of the invited user
- user_permission: permission level
- account_status: 0 = Invited user has never logged in, 1 = Invited user has logged at least once

2018-08-27 08:35 UTC, simonmeyerrr requested changes
There are changes to be made.
You don't need to put a variable name from the return prototype of a function (example: you always put `err error` when you could just put `error`)
the  `inviteUserWithValidBody` function is not well readable, is there not a way to improve it?

2018-08-27 08:35 UTC, simonmeyerrr commented on db/migration/0011_account_sharing.sql
> +  CONSTRAINT foreign_aws_account FOREIGN KEY (account_id) REFERENCES aws_account(id) ON DELETE CASCADE,
bad alignment on the 3 lines

2018-08-27 08:35 UTC, simonmeyerrr commented on db/schema.sql
> +  CONSTRAINT foreign_aws_account FOREIGN KEY (account_id) REFERENCES aws_account(id) ON DELETE CASCADE,
same

2018-08-27 08:35 UTC, simonmeyerrr commented on users/shared_account.go
> +	res, err := db.Exec(sqlstr, accountId, ownerId, guestId, permissionLevel, 0)
use `_, err := ...` instand of `res, err := ...    /   _ = res`

2018-08-27 08:35 UTC, simonmeyerrr commented on users/shared_account.go
> +	if err != nil {
this condition is useless, you can just make `return err` in both case

2018-08-27 08:35 UTC, simonmeyerrr commented on users/shared_account.go
> +			logger.Warning("Error occured while adding account to an newly created user.", err)
Why Warning and not Error ? use `err.Error`

2018-08-27 08:35 UTC, simonmeyerrr commented on users/shared_account.go
> +		logger.Warning("Error occured while creating an automatic new account.", err)
same

2018-08-29 11:14 UTC, thibautcornolti requested changes

2018-08-29 11:14 UTC, thibautcornolti commented on db/migration/0011_account_sharing.sql
> +  account_id             INTEGER      NOT NULL,
`owner_id` can be found with `account_id` in the sql db. We should avoid duplicates.

2018-08-29 11:14 UTC, thibautcornolti commented on users/shared_account.go
> +}
Bad indentation

2018-08-29 11:14 UTC, thibautcornolti commented on users/shared_account.go
> +}
Use Xo.

2018-08-30 08:55 UTC, simonmeyerrr approved these changes

2018-08-30 14:51 UTC, thibautcornolti requested changes

2018-08-30 14:51 UTC, thibautcornolti commented on users/shared_account.go
> +}
I see a lot of errors, you should pack them in the top of the file
```
var (
   ...
)
```
(see `users/auth.go`)

2018-08-30 15:40 UTC, thibautcornolti approved these changes

2018-08-30 15:40 UTC, merged